### ISSUE TITLE
Access denied at the middle of the installation

### ISSUE THREAD

**Issue by Mouaz** [elixir-lang/elixir-windows-setup#16]
### Environment

* Elixir & Erlang/OTP versions : 1.10.3 & OTP 21.3 
* Operating system: Windows 10
* Running the windows installer with admin priviliges

### Current behavior
At the middle of the installation the following pop up appears

![image](https://user-images.githubusercontent.com/4012266/91662149-c19bab80-eae0-11ea-935f-a4db8e32d023.png)

### Expected behavior

Run flawlessly like everything else with elixir :)

**Comment by Mouaz** [comment]
Thanks for transferring the issue. Which script are you referring to? and how to find it? since as you see the path in the pop up is a temporary installation path.

**Comment by josevalim** [comment]
It is temporary but it often lingers there until the OS cleans it up. So to be clear:

1. Can you try it as a non-admin?
2. As an admin, can you try running the installer directly (if it is still there?)

**Comment by Mouaz** [comment]
I tried the [last release](https://github.com/elixir-lang/elixir-windows-setup/releases/tag/v2.1) instead and it was installed successfully. I presume that the version on [installation page](https://elixir-lang.org/install.html) is not updated

**Comment by Mouaz** [comment]
It is temporary but it often lingers there until the OS cleans it up. So to be clear:

Can you try it as a non-admin? _I have to be admin to install stuff_
As an admin, can you try running the installer directly (if it is still there?) _That what I did previously_

**Comment by josevalim** [comment]
Thanks, i have updated the link!

**Comment by chyndman** [comment]
The link update (https://github.com/elixir-lang/elixir-lang.github.com/commit/ce31711ff4acef46fd8955e88478fb5b356df338) shouldn't have an effect because the `elixir-websetup.exe` file hosted on hex is the same as the 2.1 release on GitHub (I checked that their MD5 hashes match).

So in case your issue still isn't resolved, try checking the "Defer installation (advanced)" checkbox on the "Select Additional Tasks" page. This will produce the `elixir-v1.10.4-setup.exe` in the same directory as `elixir-websetup.exe` on your PC, and you then can run that manually. See https://github.com/elixir-lang/elixir-windows-setup#structure for technical details.
