### ISSUE TITLE
Elixir/Erlang Installation Mismatch

### ISSUE THREAD

**Issue by RoboZoom** [elixir-lang/elixir-windows-setup#27]
Current installer offers mismatched OTP/Elixir builds.  

Per this issue (https://github.com/elixir-lang/elixir/issues/12153), OTP v25 and Elixir v1.14 must be matched.  The current installer installs OTP v24 instead of OTP v25.

**Comment by josevalim** [comment]
Hi @RoboZoom, I could not reproduce this. The installer asks me which Erlang version to install and it shows Erlang/OTP 25 in the list. Perhaps you had something already installed? Can you please show a print of your screens?

**Comment by josevalim** [comment]
I could confirm that, if Erlang is already installed, we don't prompt to update it. We would need to address this.

**Comment by RoboZoom** [comment]
This tracks with my experience.  I thought, given the installer prompts, that Erlang was being automatically installed in the background.  I did experience this issue when updating a preexisting Elixir installation on my machine.  

This being said, I do believe that while troubleshooting, I manually removed Elixir (and I thought Erlang) and attempted a fresh install. I will try to reproduce in the morning and report my findings (with screenshots to assist).

**Comment by RoboZoom** [comment]
I reproduced the installation process this morning.  The start state was that I had Elixir/Erlang/OTP installed with Scoop (under a `C:/Users/...` directory path), however my system-wide state was clean.  

I ran through the installation process, and then reinstallation process and in both cases the result was the same.  Elixir was installed, Erlang/OTP was not.

<img width="418" alt="Erl Screen 1" src="https://user-images.githubusercontent.com/56803986/204804086-c31785b5-9fdd-4fb4-968b-f9288752f420.png">

<img width="440" alt="Erl Screen 2" src="https://user-images.githubusercontent.com/56803986/204804126-53c762a3-325e-404d-bb1c-9008c6fb7491.png">

As shown in the screen shots, the installer definitely leads me to believe that Erlang is being loaded.

<img width="398" alt="Erl Screen 3" src="https://user-images.githubusercontent.com/56803986/204804248-df133490-8c10-4729-9a35-8e21ae68be7d.png">

The summary of tasks indicate that the Erlang folder should be appended to PATH.  

<img width="629" alt="Erl Screen 4" src="https://user-images.githubusercontent.com/56803986/204804367-6df8775a-104c-4610-bef2-819677607e7e.png">

The output is that there is no `Erlang OTP` folder.

I believe that my problem before was that my previous Erlang version was still present.  However if I had started from scratch, Erlang would be straight up missing (unless my Scoop installation is detected via the installer).

**Comment by josevalim** [comment]
Thanks for the follow up!

**Comment by RoboZoom** [comment]
> The installer does try to detect the current Erlang version. If one is found, it doesn't ask you to update it. We should change it so it always asks if you want to update or not. :)

Thanks!  Where does it look to detect a current Erlang Installation?

**Comment by josevalim** [comment]
From my understand of the code, it looks in the Windows Registry for certain keys added by the Erlang installer.

**Comment by RoboZoom** [comment]
That tracks - and interestingly, the registry keys (for me) are pointed at folders that no longer exist.  It was not pointing at my current installation, but my earlier removed installations.  

It might be helpful to also detect whether the paths in the registry keys are valid (so as to assert whether Erlang must be installed), or whether an update prompt is desirable.  

I'm not familiar with the installer scripting, but I will see if I can help out.

**Comment by josevalim** [comment]
> It might be helpful to also detect whether the paths in the registry keys are valid (so as to assert whether Erlang must be installed), or whether an update prompt is desirable.

Ah, noted! /cc @chyndman

**Comment by chyndman** [comment]
Thanks for reporting and investigating! In src/ErlangInstall.iss we just check whether `HKEY_LOCAL_MACHINE\SOFTWARE\(Wow6432Node\)Ericsson\Erlang` exists or not. We use this in ElixirWeb.iss to show or hide the Erlang install option.

Sounds like what we want instead is for Erlang installation to always be offered; perhaps also allow the user to select a version like we offer for Elixir, and then maybe emit a warning if something looks mismatched or Erlang might already be installed.

I plan to address this when time permits. There's some other updates I'll need to perform first due to upstream Inno Setup changes.

**Comment by kotsius** [comment]
José, by way of feedback and in reply to your [forum post](https://elixirforum.com/t/lower-the-initial-barrier-by-using-ets-and-not-postgresql-for-phoenix-examples/53287/14), it was this issue that forced me to have Erlang installed separately on my Windows machine. I cannot remember why I installed Erlang, but once I did, there was no way out. Not until Chris pointed to the HKEY_LOCAL_MACHINE\SOFTWARE\(Wow6432Node\)Ericsson\Erlang registry key. Well, it only took me 5 years to find out...

**Comment by chyndman** [comment]
Thanks for the reminder, I'd forgotten to follow up on this task. I just pushed [version 2.4](https://github.com/elixir-lang/elixir-windows-setup/releases/tag/v2.4) which at least gives the option to install Erlang even if the installer thinks it's already present. There are other enhancements we can make, but this change alone at least gives a "way out" for people with existing installs.

**Comment by josevalim** [comment]
This is awesome @chyndman, thank you so much! I have one last suggestion, if possible.

I have added a column named `min_otp_release` to `elixir.csv`, do you think it would be possible to either:

  * Check what is the Erlang version currently installed and keep the checkbox checked if is older than the one necessary?

  * If that's too tricky (for example, maybe the Erlang version is not in the registry), what do you think about changing the flow a little bit to force the users to make a decision? Instead of a checkbox, we can have a "Skip" button at the bottom. And then if Erlang is already installed we just show a warning saying: "There is already an Erlang/OTP installed on your machine. You may skip this step but note Elixir vX.Y.Z requires Erlang/OTP MIN or later." - the reason for this is because if someone does not care and just wants to press "next, next, next", they will always install it, which is more likely to work than accidentally skipping the step because the checkbox is disabled.

What do you think?

Thank you and happy new year! :heart: 🍾

**Comment by chyndman** [comment]
Here's what the Tasks page looks like:

![image](https://user-images.githubusercontent.com/6843572/213874070-d059808c-d0d7-431d-be25-2e4db7b1c1e5.png)

We can't really change to a Skip button, but what we can do is throw up a dialog box when the user selects Next. Here we can let the user know there's a problem and let them reconsider. Here's a sample:

![image](https://user-images.githubusercontent.com/6843572/213874571-fb151f78-0778-4f60-9057-f1b8a931c666.png)

As for the version check, would it be possible to use the ERTS version in `elixir.csv`? I don't know which one Elixir cares more about. Here's what the registry looks like when I install OTP 25.2.1:

![image](https://user-images.githubusercontent.com/6843572/213874787-3b43b85e-5994-4a1c-a0c9-bd9c541b62ca.png)

There's also an `Install.ini` file in the Erlang folder:
```ini
[Install]
VSN=13.1.4
SYSTEM_VSN=25
```

We could translate between OTP and ERTS using `erlang.csv` but using ERTS might be more reliable especially when users have multiple Erlang installs side by side.

**Comment by josevalim** [comment]
So what if we keep the checkbox always checked and, if they select to defer, we show the warning right below the checkbox saying they need to have at least certain OTP version? :)

**Comment by WalterMinorsJR2** [comment]
I wanted to bring up an issue that I noticed with the current installer for Elixir/Erlang. It seems that there is a mismatch between the OTP and Elixir builds. According to this issue on GitHub (elixir-lang/elixir#12153), OTP version 25 and Elixir version 1.14 must be matched. However, the current installer is installing OTP version 24 instead of version 25.

**Comment by chyndman** [comment]
The Elixir installer uses only the first row of https://github.com/elixir-lang/elixir-lang.github.com/blob/main/erlang.csv to determine which Erlang installer to employ. It was last updated September 2022 to include OTP 25. If you try again recently it should offer this version.

**Comment by josevalim** [comment]
We are now building and shipping offline Elixir installers per Erlang/OTP version which are built as part of CI. See the up to date instructions on elixir-lang.org to learn more. :)
